install: add fallback to codeberg to workaround github api rate limiting

diff --git a/assets/install b/assets/install
--- a/assets/install
+++ b/assets/install
@@ -152,11 +152,14 @@ esac
 
 # get latest version tag from github releases api
 version=$(curl -s "https://api.github.com/repos/$repo/releases/latest" | jq -r .tag_name)
-[ -z "$version" ] && {
-    version=$(curl -s https://git.flow-control.dev/api/v1/repos/$repo/releases/latest | jq -r .tag_name)
-    [ -z "$version" ] && {
-        echo "failed to fetch $title latest version from github or flow-control.dev"
-        exit 1
+[ -z "$version" ] || [ "$version" = "null" ] && {
+    version=$(curl -s https://codeberg.org/api/v1/repos/neurocyte/flow-nightly/releases/latest | jq -r .tag_name)
+    [ -z "$version" ] || [ "$version" = "null" ] && {
+        version=$(curl -s https://git.flow-control.dev/api/v1/repos/$repo/releases/latest | jq -r .tag_name)
+        [ -z "$version" ] || [ "$version" = "null" ] && {
+            echo "failed to fetch $title latest version from github, codeberg or flow-control.dev"
+            exit 1
+        }
     }
 }
 title="$title $version"
